server:
  port: 8080
  error:
    include-message: always
spring:
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    username: postgres
    password: hellomy1q
    url: jdbc:postgresql://localhost:5432/task_manager
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: warn
    org:
      springframework: info
    com:
      example:
        task_manager: debug
  pattern:
    dateformat: dd-MM-yyyy
  file:
    name: app.log
jwt:
  secretKey: SupperKey
  expireTime: 86400000